version: '3.1'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        privileged: true
        volumes:
            - ../:/var/www:Z
        ports:
            - "9000:9000"
    mysql:
        image: mysql:8.0
        privileged: true
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        volumes:
            - $PWD/mysql/data:/var/lib/mysql
            - $PWD/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            MYSQL_DATABASE: redis-example
            MYSQL_ROOT_PASSWORD: password
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
    web:
        image: nginx
        restart: always
        privileged: true
        volumes:
            - ../:/var/www
            - ../storage/logs/nginx:/var/log/nginx:Z
            - $PWD/nginx/conf.d:/etc/nginx/conf.d:Z
            - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf:Z
        ports:
            - "8080:80"
        links:
            - app
    composer:
        restart: 'no'
        image: composer:latest
        command: ['install']
        volumes:
            - ../.:/app
    redis:
        image: redis
        restart: always
        privileged: true
        command: redis-server --requirepass password
        volumes:
            - $PWD/redis/data:/var/lib/redis
            - $PWD/redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - "6379"
